language: rust
rust: stable
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  cargo: true
before_script:
  - rustup target add thumbv7m-none-eabi
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  - RUSTFLAGS="-D warnings" cargo clippy
  - cargo test
  - cargo build --release
  - strip target/release/the-elements
  - ls -lh target/release/the-elements
